const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o)),STORE='vacationPlannerV03',OLD_STORE='vacationPlannerV02';
function normalize(data){const base=clone(window.DEFAULT_DATA);const d=data&&typeof data==='object'?data:{};return {users:Array.isArray(d.users)?d.users:base.users,departments:Array.isArray(d.departments)?d.departments:base.departments,employees:Array.isArray(d.employees)?d.employees:base.employees,vacations:Array.isArray(d.vacations)?d.vacations:base.vacations,moves:Array.isArray(d.moves)?d.moves:base.moves}}
function loadState(){try{const saved=localStorage.getItem(STORE)||localStorage.getItem(OLD_STORE);return saved?normalize(JSON.parse(saved)):normalize(window.DEFAULT_DATA)}catch{return normalize(window.DEFAULT_DATA)}}
let state=loadState();
function saveState(){localStorage.setItem(STORE,JSON.stringify(state))}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function localDate(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmt(s){return localDate(s).toLocaleDateString('de-DE')}
function period(from,to){return `${fmt(from)}–${fmt(to)}`}
function employee(id){return state.employees.find(e=>e.id===Number(id))}
function vacationsFor(id){return state.vacations.filter(v=>v.employeeId===Number(id))}
function inRange(date,from,to){return date>=localDate(from)&&date<=localDate(to)}
function workingDays(from,to){let n=0,d=localDate(from),end=localDate(to);for(;d<=end;d.setDate(d.getDate()+1))if(![0,6].includes(d.getDay())&&!holidayName(d))n++;return n}
function easterSunday(year){const a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return new Date(year,month-1,day)}
function holidayName(date){const md=`${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,fixed={'01-01':'Neujahr','03-08':'Internationaler Frauentag','05-01':'Tag der Arbeit','10-03':'Tag der Deutschen Einheit','12-25':'1. Weihnachtstag','12-26':'2. Weihnachtstag'};if(fixed[md])return fixed[md];const e=easterSunday(date.getFullYear()),diff=Math.round((date-e)/86400000);return ({[-2]:'Karfreitag',[1]:'Ostermontag',[39]:'Christi Himmelfahrt',[50]:'Pfingstmontag'})[diff]||''}
function init(){fillLogin();setDefaults();bind();renderAll()}
function fillLogin(){$('loginName').innerHTML=state.users.map(u=>`<option>${esc(u.name)}</option>`).join('')}
function setDefaults(){const d=new Date();$('monthFilter').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;$('weekDate').value=iso(d);$('vacationFrom').value=$('vacationTo').value=iso(d)}
function bind(){
 $('loginButton').onclick=login;$('loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutButton').onclick=()=>{$('application').classList.add('hidden');$('loginPage').classList.remove('hidden');$('loginPin').value=''};
 $('navigation').onclick=e=>{const p=e.target.dataset.page;if(!p)return;document.querySelectorAll('#navigation button').forEach(b=>b.classList.toggle('active',b===e.target));document.querySelectorAll('.page').forEach(s=>s.classList.add('hidden'));$('page-'+p).classList.remove('hidden');renderAll()};
 $('departmentFilter').onchange=renderCalendar;$('monthFilter').onchange=renderCalendar;$('weekDate').onchange=renderWeek;$('showVacationForm').onclick=openNewVacation;$('cancelVacation').onclick=closeVacationForm;$('saveVacation').onclick=saveVacation;$('addEmployee').onclick=addEmployee;$('addMove').onclick=addMove;$('resetData').onclick=resetData;$('backupExport').onclick=exportBackup;$('backupImport').onchange=importBackup;$('exportCsv').onclick=exportCsv;
}
function login(){const u=state.users.find(x=>x.name===$('loginName').value&&x.pin===$('loginPin').value);if(!u){$('loginError').textContent='Name oder PIN ist nicht korrekt.';return}$('loginError').textContent='';$('loggedInUser').textContent=`${u.name} · ${u.role==='admin'?'Admin':'Leitung'}`;$('loginPage').classList.add('hidden');$('application').classList.remove('hidden');renderAll()}
function renderAll(){fillSelects();renderDashboard();renderEmployees();renderCalendar();renderWeek();renderLeaders();renderHistory()}
function fillSelects(){const deps=state.departments.map(d=>`<option>${esc(d)}</option>`).join('');const current=$('departmentFilter').value;$('departmentFilter').innerHTML=deps;if(state.departments.includes(current))$('departmentFilter').value=current;$('employeeDepartment').innerHTML=deps;const opts=state.employees.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');$('moveEmployee').innerHTML=opts;$('employeeSubstitute').innerHTML='<option value="">Keine</option>'+state.employees.map(e=>`<option>${esc(e.name)}</option>`).join('')}
function renderDashboard(){$('departmentCount').textContent=state.departments.length;$('employeeCount').textContent=state.employees.length;$('leaderCount').textContent=state.employees.filter(e=>e.leader).length;$('plannedDays').textContent=state.vacations.reduce((s,v)=>s+workingDays(v.from,v.to),0);$('todayLabel').textContent=new Date().toLocaleDateString('de-DE');const warns=[];state.departments.forEach(dep=>{const m=maxOverlapForDepartment(dep);if(m>=2)warns.push(`<div class="warning ${m>=3?'warning-danger':''}"><strong>${esc(dep)}:</strong> Bis zu ${m} Personen gleichzeitig abwesend.</div>`)});const l=leaderOverlapCount();if(l>=2)warns.push(`<div class="warning warning-danger"><strong>Leiterplan:</strong> Bis zu ${l} Leiter gleichzeitig abwesend.</div>`);$('warnings').innerHTML=warns.join('')||'<div class="warning"><strong>Alles in Ordnung:</strong> Keine kritischen Überschneidungen gefunden.</div>';const today=new Date();const rows=state.vacations.filter(v=>localDate(v.to)>=today).sort((a,b)=>localDate(a.from)-localDate(b.from)).slice(0,8);$('upcomingTable').innerHTML='<thead><tr><th>Mitarbeiter</th><th>Abteilung</th><th>Zeitraum</th><th>Art</th></tr></thead><tbody>'+rows.map(v=>{const e=employee(v.employeeId);return `<tr><td>${esc(e?.name)}</td><td>${esc(e?.department)}</td><td>${period(v.from,v.to)}</td><td>${esc(v.type)}</td></tr>`}).join('')+'</tbody>'}
function maxOverlap(vacs){let max=0;for(const v of vacs){for(let d=localDate(v.from),end=localDate(v.to);d<=end;d.setDate(d.getDate()+1))max=Math.max(max,vacs.filter(x=>inRange(new Date(d),x.from,x.to)).length)}return max}
function maxOverlapForDepartment(dep){const ids=state.employees.filter(e=>e.department===dep).map(e=>e.id);return maxOverlap(state.vacations.filter(v=>ids.includes(v.employeeId)))}
function leaderOverlapCount(){const ids=state.employees.filter(e=>e.leader).map(e=>e.id);return maxOverlap(state.vacations.filter(v=>ids.includes(v.employeeId)))}
function renderEmployees(){const table=$('employeeTable');$('employeeListCount').textContent=`${state.employees.length} Mitarbeiter`;table.innerHTML='<thead><tr><th>Name</th><th>Abteilung</th><th>Stunden</th><th>Jahresurlaub</th><th>Geplant</th><th>Rest</th><th>Leiter</th><th>Vertretung</th><th>Aktion</th></tr></thead><tbody>'+state.employees.map(e=>{const planned=vacationsFor(e.id).reduce((s,v)=>s+workingDays(v.from,v.to),0),rest=e.vacationDays-planned;return `<tr><td>${esc(e.name)}</td><td>${esc(e.department)}</td><td>${e.hours}</td><td>${e.vacationDays}</td><td>${planned}</td><td class="${rest<0?'negative':'positive'}">${rest}</td><td>${e.leader?'Ja':'Nein'}</td><td>${esc(e.substitute||'–')}</td><td><button class="button tiny danger" onclick="deleteEmployee(${e.id})">Löschen</button></td></tr>`}).join('')+'</tbody>';if(!state.employees.length)table.innerHTML='<tbody><tr><td>Keine Mitarbeiter vorhanden.</td></tr></tbody>'}
function addEmployee(){const name=$('employeeName').value.trim();if(!name)return alert('Bitte einen Namen eingeben.');state.employees.push({id:Date.now(),name,department:$('employeeDepartment').value,hours:Number($('employeeHours').value),vacationDays:Number($('employeeVacationDays').value),leader:$('employeeLeader').checked,substitute:$('employeeSubstitute').value});saveState();$('employeeName').value='';$('employeeLeader').checked=false;renderAll()}
window.deleteEmployee=id=>{if(!confirm('Mitarbeiter und zugehörige Urlaubseinträge wirklich löschen?'))return;state.employees=state.employees.filter(e=>e.id!==id);state.vacations=state.vacations.filter(v=>v.employeeId!==id);state.moves=state.moves.filter(m=>m.employeeId!==id);saveState();renderAll()}
function renderCalendar(){const dep=$('departmentFilter').value||state.departments[0],[year,month]=$('monthFilter').value.split('-').map(Number),emps=state.employees.filter(e=>e.department===dep),days=new Date(year,month,0).getDate();$('vacationEmployee').innerHTML=emps.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');let h='<thead><tr><th class="employee-name">Mitarbeiter</th>';for(let d=1;d<=days;d++)h+=`<th>${d}</th>`;h+='</tr></thead><tbody>';for(const e of emps){h+=`<tr><td class="employee-name">${esc(e.name)} ${e.leader?'<span class="badge leader-badge">Leiter</span>':''}</td>`;for(let d=1;d<=days;d++){const date=new Date(year,month-1,d),vac=vacationsFor(e.id).find(v=>inRange(date,v.from,v.to)),overlap=countDepartmentAbsence(dep,date);let cls=[0,6].includes(date.getDay())?'weekend':'';if(holidayName(date))cls='holiday';if(vac)cls=overlap>=3?'critical':'vacation';const code=vac?({Urlaub:'U',Sonderurlaub:'S',Fortbildung:'F',Unbezahlt:'N'}[vac.type]||'U'):'';h+=`<td class="${cls}" title="${esc(vac?.note||holidayName(date))}">${code}</td>`}h+='</tr>'}h+='</tbody>';$('calendarTable').innerHTML=h;const max=maxOverlapForDepartment(dep);$('calendarWarning').innerHTML=max>=2?`<div class="warning ${max>=3?'warning-danger':''}"><strong>Besetzungshinweis:</strong> In ${esc(dep)} sind bis zu ${max} Personen gleichzeitig abwesend.</div>`:'';renderVacationList(dep)}
function countDepartmentAbsence(dep,date){const ids=state.employees.filter(e=>e.department===dep).map(e=>e.id);return state.vacations.filter(v=>ids.includes(v.employeeId)&&inRange(date,v.from,v.to)).length}
function renderVacationList(dep){const ids=state.employees.filter(e=>e.department===dep).map(e=>e.id),rows=state.vacations.filter(v=>ids.includes(v.employeeId)).sort((a,b)=>localDate(a.from)-localDate(b.from));$('vacationList').innerHTML='<thead><tr><th>Mitarbeiter</th><th>Von</th><th>Bis</th><th>Arbeitstage</th><th>Art</th><th>Notiz</th><th>Aktionen</th></tr></thead><tbody>'+rows.map(v=>`<tr><td>${esc(employee(v.employeeId)?.name)}</td><td>${fmt(v.from)}</td><td>${fmt(v.to)}</td><td>${workingDays(v.from,v.to)}</td><td>${esc(v.type)}</td><td>${esc(v.note||'–')}</td><td><div class="actions compact"><button class="button tiny" onclick="moveVacation(${v.id})">Verschieben</button><button class="button tiny danger" onclick="deleteVacation(${v.id})">Löschen</button></div></td></tr>`).join('')+'</tbody>';if(!rows.length)$('vacationList').innerHTML+='<tfoot><tr><td colspan="7" class="muted">Für diese Abteilung sind noch keine Urlaubseinträge vorhanden.</td></tr></tfoot>'}
function openNewVacation(){$('editingVacationId').value='';$('vacationFormTitle').textContent='Neuen Urlaub eintragen';$('saveVacation').textContent='Urlaub speichern';$('vacationNote').value='';$('vacationForm').classList.remove('hidden')}
function closeVacationForm(){$('vacationForm').classList.add('hidden');$('editingVacationId').value=''}
function saveVacation(){const employeeId=Number($('vacationEmployee').value),from=$('vacationFrom').value,to=$('vacationTo').value;if(!employeeId||!from||!to)return alert('Bitte alle Pflichtfelder ausfüllen.');if(localDate(to)<localDate(from))return alert('Das Enddatum muss nach dem Startdatum liegen.');const editingId=Number($('editingVacationId').value);if(editingId){const v=state.vacations.find(x=>x.id===editingId);if(!v)return;const oldFrom=v.from,oldTo=v.to;const reason=prompt('Grund für die Verschiebung:','Personelle Planung')||'Nicht angegeben';const initiator=confirm('Wurde die Verschiebung vom Betrieb veranlasst?\nOK = Betrieb, Abbrechen = Mitarbeiter')?'Betrieb':'Mitarbeiter';v.employeeId=employeeId;v.from=from;v.to=to;v.type=$('vacationType').value;v.note=$('vacationNote').value.trim();state.moves.push({id:Date.now(),employeeId,oldPeriod:period(oldFrom,oldTo),newPeriod:period(from,to),reason,initiator});}else state.vacations.push({id:Date.now(),employeeId,from,to,type:$('vacationType').value,note:$('vacationNote').value.trim()});saveState();closeVacationForm();renderAll()}
window.moveVacation=id=>{const v=state.vacations.find(x=>x.id===id);if(!v)return;$('editingVacationId').value=String(id);$('vacationFormTitle').textContent='Urlaub verschieben';$('saveVacation').textContent='Verschiebung speichern';$('vacationEmployee').value=String(v.employeeId);$('vacationFrom').value=v.from;$('vacationTo').value=v.to;$('vacationType').value=v.type;$('vacationNote').value=v.note||'';$('vacationForm').classList.remove('hidden');$('vacationForm').scrollIntoView({behavior:'smooth',block:'center'})}
window.deleteVacation=id=>{if(!confirm('Urlaubseintrag wirklich löschen?'))return;state.vacations=state.vacations.filter(v=>v.id!==id);saveState();renderAll()}
function renderWeek(){const selected=localDate($('weekDate').value),day=(selected.getDay()+6)%7,monday=new Date(selected);monday.setDate(selected.getDate()-day);const dates=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);return d});$('weekSummary').innerHTML=`<p class="muted">${dates[0].toLocaleDateString('de-DE')} bis ${dates[6].toLocaleDateString('de-DE')}</p>`;let h='<thead><tr><th>Abteilung</th>'+dates.map(d=>`<th>${d.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}</th>`).join('')+'</tr></thead><tbody>';for(const dep of state.departments){h+=`<tr><td>${esc(dep)}</td>`;for(const d of dates){const n=countDepartmentAbsence(dep,d);h+=`<td class="${n>=3?'critical':n>=1?'vacation':''}">${n||'–'}</td>`}h+='</tr>'}$('weekTable').innerHTML=h+'</tbody>'}
function renderLeaders(){const leaders=state.employees.filter(e=>e.leader);$('leaderTable').innerHTML='<thead><tr><th>Name</th><th>Abteilung</th><th>Vertretung</th><th>Urlaubszeiträume</th><th>Betriebliche Verschiebungen</th></tr></thead><tbody>'+leaders.map(e=>`<tr><td>${esc(e.name)}</td><td>${esc(e.department)}</td><td>${esc(e.substitute||'–')}</td><td>${vacationsFor(e.id).map(v=>period(v.from,v.to)).join('<br>')||'–'}</td><td>${state.moves.filter(m=>m.employeeId===e.id&&m.initiator==='Betrieb').length}</td></tr>`).join('')+'</tbody>';const c=leaderOverlapCount();$('leaderWarnings').innerHTML=c>=2?`<div class="warning warning-danger"><strong>Warnung:</strong> Bis zu ${c} Leiter sind gleichzeitig abwesend.</div>`:'<div class="warning">Keine kritische Leiterüberschneidung.</div>'}
function renderHistory(){$('historyTable').innerHTML='<thead><tr><th>Mitarbeiter</th><th>Alter Zeitraum</th><th>Neuer Zeitraum</th><th>Grund</th><th>Veranlasst durch</th></tr></thead><tbody>'+state.moves.map(m=>`<tr><td>${esc(employee(m.employeeId)?.name||'Gelöscht')}</td><td>${esc(m.oldPeriod)}</td><td>${esc(m.newPeriod)}</td><td>${esc(m.reason)}</td><td>${esc(m.initiator)}</td></tr>`).join('')+'</tbody>';const counts={};state.moves.filter(m=>m.initiator==='Betrieb').forEach(m=>counts[m.employeeId]=(counts[m.employeeId]||0)+1);$('fairnessWarnings').innerHTML=Object.entries(counts).filter(([,c])=>c>=2).map(([id,c])=>`<div class="warning"><strong>Fairnesshinweis:</strong> ${esc(employee(id)?.name||'Unbekannt')} hat bereits ${c} betriebliche Verschiebungen.</div>`).join('')}
function addMove(){const employeeId=Number($('moveEmployee').value),oldPeriod=$('moveOld').value.trim(),newPeriod=$('moveNew').value.trim(),reason=$('moveReason').value.trim();if(!employeeId||!oldPeriod||!newPeriod||!reason)return alert('Bitte alle Felder ausfüllen.');state.moves.push({id:Date.now(),employeeId,oldPeriod,newPeriod,reason,initiator:$('moveInitiator').value});saveState();$('moveOld').value=$('moveNew').value=$('moveReason').value='';renderAll()}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportBackup(){download(`urlaubsplaner-sicherung-${iso(new Date())}.json`,JSON.stringify(state,null,2),'application/json');$('backupStatus').textContent='Sicherung wurde erstellt.'}
function importBackup(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{state=normalize(JSON.parse(r.result));saveState();fillLogin();renderAll();$('backupStatus').textContent='Sicherung erfolgreich importiert.'}catch{$('backupStatus').textContent='Die Datei ist keine gültige Urlaubsplaner-Sicherung.'}};r.readAsText(file)}
function exportCsv(){const dep=$('departmentFilter').value,ids=state.employees.filter(e=>e.department===dep).map(e=>e.id),rows=[['Mitarbeiter','Abteilung','Von','Bis','Arbeitstage','Art','Notiz']];state.vacations.filter(v=>ids.includes(v.employeeId)).forEach(v=>rows.push([employee(v.employeeId)?.name,dep,v.from,v.to,workingDays(v.from,v.to),v.type,v.note]));const csv='\ufeff'+rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(';')).join('\r\n');download(`Urlaubsplan-${dep}.csv`,csv,'text/csv;charset=utf-8')}
function resetData(){if(!confirm('Alle lokalen Änderungen löschen und Testdaten wiederherstellen?'))return;state=normalize(window.DEFAULT_DATA);localStorage.removeItem(OLD_STORE);saveState();fillLogin();renderAll();$('backupStatus').textContent='Testdaten wurden wiederhergestellt.'}
init();
