const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o));
const STORE='vacationPlannerV05',OLD_STORES=['vacationPlannerV04','vacationPlannerV03','vacationPlannerV02'];
let currentUser=null;
function normalize(raw){const b=clone(window.DEFAULT_DATA),d=raw&&typeof raw==='object'?raw:{};const departments=Array.isArray(d.departments)&&d.departments.length?d.departments:b.departments;const settings={...(b.departmentSettings||{}),...(d.departmentSettings||{})};departments.forEach(x=>{if(settings[x]==null)settings[x]=2});return{users:Array.isArray(d.users)?d.users:b.users,departments,departmentSettings:settings,employees:(Array.isArray(d.employees)?d.employees:b.employees).map(e=>({...e,carryover:Number(e.carryover||0)})),vacations:(Array.isArray(d.vacations)?d.vacations:b.vacations).map(v=>({...v,status:v.status||'Genehmigt',scope:v.scope||'full'})),moves:Array.isArray(d.moves)?d.moves:b.moves}}
function loadState(){try{let raw=localStorage.getItem(STORE);if(!raw)for(const k of OLD_STORES){raw=localStorage.getItem(k);if(raw)break}return raw?normalize(JSON.parse(raw)):normalize(window.DEFAULT_DATA)}catch{return normalize(window.DEFAULT_DATA)}}
let state=loadState();
function saveState(){localStorage.setItem(STORE,JSON.stringify(state))}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function localDate(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmt(s){return localDate(s).toLocaleDateString('de-DE')}
function period(a,b){return `${fmt(a)}–${fmt(b)}`}
function emp(id){return state.employees.find(e=>e.id===Number(id))}
function vacsFor(id){return state.vacations.filter(v=>v.employeeId===Number(id))}
function inRange(d,a,b){return d>=localDate(a)&&d<=localDate(b)}
function easterSunday(y){const a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),day=(h+l-7*m+114)%31+1;return new Date(y,mo-1,day)}
function holidayName(date){const md=`${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,fixed={'01-01':'Neujahr','03-08':'Internationaler Frauentag','05-01':'Tag der Arbeit','10-03':'Tag der Deutschen Einheit','12-25':'1. Weihnachtstag','12-26':'2. Weihnachtstag'};if(fixed[md])return fixed[md];const e=easterSunday(date.getFullYear()),diff=Math.round((date-e)/86400000);return({[-2]:'Karfreitag',[1]:'Ostermontag',[39]:'Christi Himmelfahrt',[50]:'Pfingstmontag'})[diff]||''}
function workingDays(a,b){let n=0,d=localDate(a),end=localDate(b);for(;d<=end;d.setDate(d.getDate()+1))if(![0,6].includes(d.getDay())&&!holidayName(d))n++;return n}
function vacationDays(v){const days=workingDays(v.from,v.to);return v.scope==='full'?days:Math.min(.5,days*.5)}
function countsAgainstVacation(v){return v.type==='Urlaub'}
function statusBadge(s){const c=s==='Genehmigt'?'approved':s==='Beantragt'?'pending':'planned';return `<span class="badge ${c}">${esc(s)}</span>`}
function init(){fillLogin();setDefaults();bind();renderAll()}
function fillLogin(){$('loginName').innerHTML=state.users.map(u=>`<option>${esc(u.name)}</option>`).join('')}
function setDefaults(){const d=new Date();$('monthFilter').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;$('weekDate').value=iso(d);$('vacationFrom').value=$('vacationTo').value=iso(d)}
function bind(){
 $('loginButton').onclick=login;$('loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutButton').onclick=()=>{$('application').classList.add('hidden');$('loginPage').classList.remove('hidden');$('loginPin').value='';currentUser=null};
 $('navigation').onclick=e=>{const p=e.target.dataset.page;if(!p)return;document.querySelectorAll('#navigation button').forEach(b=>b.classList.toggle('active',b===e.target));document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('page-'+p).classList.remove('hidden');renderAll()};
 $('departmentFilter').onchange=renderCalendar;$('monthFilter').onchange=renderCalendar;$('weekDate').onchange=renderWeek;$('showVacationForm').onclick=openNewVacation;$('cancelVacation').onclick=closeVacationForm;$('saveVacation').onclick=saveVacation;
 $('addEmployee').onclick=saveEmployee;$('cancelEmployeeEdit').onclick=clearEmployeeForm;$('addMove').onclick=addMove;$('addDepartment').onclick=addDepartment;
 $('resetData').onclick=resetData;$('backupExport').onclick=exportBackup;$('backupImport').onchange=importBackup;$('exportCsv').onclick=exportCsv;
}
function login(){const u=state.users.find(x=>x.name===$('loginName').value&&x.pin===$('loginPin').value);if(!u){$('loginError').textContent='Name oder PIN ist nicht korrekt.';return}currentUser=u;$('loginError').textContent='';$('loggedInUser').textContent=`${u.name} · ${u.role==='admin'?'Admin':'Leitung'}`;$('loginPage').classList.add('hidden');$('application').classList.remove('hidden');renderAll()}
function renderAll(){fillSelects();renderDashboard();renderEmployees();renderCalendar();renderWeek();renderLeaders();renderHistory();renderDepartments()}
function fillSelects(){const deps=state.departments.map(d=>`<option>${esc(d)}</option>`).join(''),cur=$('departmentFilter').value;$('departmentFilter').innerHTML=deps;if(state.departments.includes(cur))$('departmentFilter').value=cur;$('employeeDepartment').innerHTML=deps;const opts=state.employees.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');$('moveEmployee').innerHTML=opts;$('employeeSubstitute').innerHTML='<option value="">Keine</option>'+state.employees.map(e=>`<option>${esc(e.name)}</option>`).join('')}
function allDates(vacs){const out=[];for(const v of vacs)for(let d=localDate(v.from),e=localDate(v.to);d<=e;d.setDate(d.getDate()+1))out.push(new Date(d));return out}
function maxOverlap(vacs){let max=0;for(const d of allDates(vacs))max=Math.max(max,vacs.filter(v=>inRange(d,v.from,v.to)&&v.status!=='Geplant').length);return max}
function maxOverlapForDepartment(dep){const ids=state.employees.filter(e=>e.department===dep).map(e=>e.id);return maxOverlap(state.vacations.filter(v=>ids.includes(v.employeeId)))}
function leaderOverlapCount(){const ids=state.employees.filter(e=>e.leader).map(e=>e.id);return maxOverlap(state.vacations.filter(v=>ids.includes(v.employeeId)))}
function bridgeWarnings(v){const result=[];for(let d=localDate(v.from),end=localDate(v.to);d<=end;d.setDate(d.getDate()+1)){const prev=new Date(d);prev.setDate(prev.getDate()-1);const next=new Date(d);next.setDate(next.getDate()+1);if(d.getDay()===1&&holidayName(prev))result.push(`Brückentag nach ${holidayName(prev)}`);if(d.getDay()===5&&holidayName(next))result.push(`Brückentag vor ${holidayName(next)}`)}return [...new Set(result)]}
function renderDashboard(){$('departmentCount').textContent=state.departments.length;$('employeeCount').textContent=state.employees.length;$('leaderCount').textContent=state.employees.filter(e=>e.leader).length;$('plannedDays').textContent=state.vacations.filter(v=>v.status==='Genehmigt'&&countsAgainstVacation(v)).reduce((s,v)=>s+vacationDays(v),0);$('todayLabel').textContent=new Date().toLocaleDateString('de-DE');const w=[];state.departments.forEach(dep=>{const m=maxOverlapForDepartment(dep);if(m>=2)w.push(`<div class="warning ${m>=3?'warning-danger':''}"><strong>${esc(dep)}:</strong> Bis zu ${m} Personen gleichzeitig abwesend.</div>`)});const l=leaderOverlapCount();if(l>=2)w.push(`<div class="warning warning-danger"><strong>Leiterplan:</strong> Bis zu ${l} Leiter gleichzeitig abwesend.</div>`);const pending=state.vacations.filter(v=>v.status==='Beantragt').length;if(pending)w.unshift(`<div class="warning"><strong>Freigaben:</strong> ${pending} Urlaubsantrag${pending===1?'':'träge'} wartet${pending===1?'':'en'} auf Entscheidung.</div>`);$('warnings').innerHTML=w.join('')||'<div class="warning"><strong>Alles in Ordnung:</strong> Keine kritischen Überschneidungen gefunden.</div>';const today=new Date();const rows=state.vacations.filter(v=>localDate(v.to)>=today).sort((a,b)=>localDate(a.from)-localDate(b.from)).slice(0,10);$('upcomingTable').innerHTML='<thead><tr><th>Mitarbeiter</th><th>Abteilung</th><th>Zeitraum</th><th>Art</th><th>Status</th></tr></thead><tbody>'+rows.map(v=>{const e=emp(v.employeeId);return `<tr><td>${esc(e?.name)}</td><td>${esc(e?.department)}</td><td>${period(v.from,v.to)}</td><td>${esc(v.type)}</td><td>${statusBadge(v.status)}</td></tr>`}).join('')+'</tbody>'}
function renderEmployees(){$('employeeListCount').textContent=`${state.employees.length} Mitarbeiter`;$('employeeTable').innerHTML='<thead><tr><th>Name</th><th>Abteilung</th><th>Stunden</th><th>Anspruch</th><th>Übertrag</th><th>Genehmigt</th><th>Rest</th><th>Leiter</th><th>Vertretung</th><th>Aktion</th></tr></thead><tbody>'+state.employees.map(e=>{const planned=vacsFor(e.id).filter(v=>v.status==='Genehmigt'&&countsAgainstVacation(v)).reduce((s,v)=>s+vacationDays(v),0),total=Number(e.vacationDays||0)+Number(e.carryover||0),rest=total-planned;return `<tr><td>${esc(e.name)}</td><td>${esc(e.department)}</td><td>${e.hours}</td><td>${e.vacationDays}</td><td>${e.carryover||0}</td><td>${planned}</td><td class="${rest<0?'negative':'positive'}">${rest}</td><td>${e.leader?'Ja':'Nein'}</td><td>${esc(e.substitute||'–')}</td><td><button class="button tiny" onclick="editEmployee(${e.id})">Bearbeiten</button> <button class="button tiny danger" onclick="deleteEmployee(${e.id})">Löschen</button></td></tr>`}).join('')+'</tbody>'}
function saveEmployee(){const name=$('employeeName').value.trim();if(!name)return alert('Bitte einen Namen eingeben.');const id=Number($('editingEmployeeId').value),obj={name,department:$('employeeDepartment').value,hours:Number($('employeeHours').value),vacationDays:Number($('employeeVacationDays').value),carryover:Number($('employeeCarryover').value||0),leader:$('employeeLeader').checked,substitute:$('employeeSubstitute').value};if(id){const e=emp(id);Object.assign(e,obj)}else state.employees.push({id:Date.now(),...obj});saveState();clearEmployeeForm();renderAll()}
window.editEmployee=id=>{const e=emp(id);if(!e)return;$('editingEmployeeId').value=id;$('employeeName').value=e.name;$('employeeDepartment').value=e.department;$('employeeHours').value=e.hours;$('employeeVacationDays').value=e.vacationDays;$('employeeCarryover').value=e.carryover||0;$('employeeLeader').checked=e.leader;$('employeeSubstitute').value=e.substitute||'';$('addEmployee').textContent='Änderungen speichern';$('cancelEmployeeEdit').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function clearEmployeeForm(){$('editingEmployeeId').value='';$('employeeName').value='';$('employeeHours').value=37;$('employeeVacationDays').value=36;$('employeeCarryover').value=0;$('employeeLeader').checked=false;$('employeeSubstitute').value='';$('addEmployee').textContent='Mitarbeiter hinzufügen';$('cancelEmployeeEdit').classList.add('hidden')}
window.deleteEmployee=id=>{if(!confirm('Mitarbeiter und zugehörige Urlaube wirklich löschen?'))return;state.employees=state.employees.filter(e=>e.id!==id);state.vacations=state.vacations.filter(v=>v.employeeId!==id);state.moves=state.moves.filter(m=>m.employeeId!==id);saveState();renderAll()}
function countDepartmentAbsence(dep,date){const ids=state.employees.filter(e=>e.department===dep).map(e=>e.id);return state.vacations.filter(v=>ids.includes(v.employeeId)&&v.status!=='Geplant'&&inRange(date,v.from,v.to)).length}
function renderCalendar(){const dep=$('departmentFilter').value||state.departments[0],parts=$('monthFilter').value.split('-').map(Number),year=parts[0],month=parts[1],emps=state.employees.filter(e=>e.department===dep),days=new Date(year,month,0).getDate();$('vacationEmployee').innerHTML=emps.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');let h='<thead><tr><th class="employee-name">Mitarbeiter</th>';for(let d=1;d<=days;d++)h+=`<th>${d}</th>`;h+='</tr></thead><tbody>';for(const e of emps){h+=`<tr><td class="employee-name">${esc(e.name)} ${e.leader?'<span class="badge leader-badge">Leiter</span>':''}</td>`;for(let d=1;d<=days;d++){const date=new Date(year,month-1,d),v=vacsFor(e.id).find(x=>inRange(date,x.from,x.to)),overlap=countDepartmentAbsence(dep,date);let cls=[0,6].includes(date.getDay())?'weekend':'';if(holidayName(date))cls='holiday';if(v)cls=v.status==='Beantragt'?'pending-cell':v.status==='Geplant'?'planned-cell':overlap>=3?'critical':'vacation';const code=v?({Urlaub:'U',Sonderurlaub:'S',Fortbildung:'F',Unbezahlt:'N',Krankheit:'K'}[v.type]||'A')+(v.scope!=='full'?'½':''):'';h+=`<td class="${cls}" title="${esc([v?.status,v?.note,holidayName(date)].filter(Boolean).join(' · '))}">${code}</td>`}h+='</tr>'}$('calendarTable').innerHTML=h+'</tbody>';const m=maxOverlapForDepartment(dep),min=Number(state.departmentSettings?.[dep]??2),total=emps.length,available=total-m,critical=available<min;$('calendarWarning').innerHTML=critical?`<div class="warning warning-danger"><strong>Mindestbesetzung unterschritten:</strong> Bei maximal ${m} Abwesenden bleiben nur ${available} von ${total} Mitarbeitenden verfügbar. Eingestellt sind mindestens ${min}.</div>`:m>=2?`<div class="warning"><strong>Besetzungshinweis:</strong> Bis zu ${m} Mitarbeiter gleichzeitig abwesend; Mindestbesetzung ${min} bleibt erfüllt.</div>`:'';renderVacationList(dep)}
function renderVacationList(dep){const ids=state.employees.filter(e=>e.department===dep).map(e=>e.id),rows=state.vacations.filter(v=>ids.includes(v.employeeId)).sort((a,b)=>localDate(a.from)-localDate(b.from));$('vacationList').innerHTML='<thead><tr><th>Mitarbeiter</th><th>Zeitraum</th><th>Tage</th><th>Umfang</th><th>Art</th><th>Status</th><th>Hinweis</th><th>Aktion</th></tr></thead><tbody>'+rows.map(v=>{const bw=bridgeWarnings(v).join(', ');return `<tr><td>${esc(emp(v.employeeId)?.name)}</td><td>${period(v.from,v.to)}</td><td>${vacationDays(v)}</td><td>${v.scope==='full'?'Ganzer Tag':'Halber Tag'}</td><td>${esc(v.type)}</td><td>${statusBadge(v.status)}</td><td>${esc(bw||v.note||'–')}</td><td><button class="button tiny" onclick="editVacation(${v.id})">Verschieben/Bearbeiten</button> ${v.status==='Beantragt'?`<button class="button tiny primary" onclick="approveVacation(${v.id})">Genehmigen</button>`:''} <button class="button tiny danger" onclick="deleteVacation(${v.id})">Löschen</button></td></tr>`}).join('')+'</tbody>'}
function openNewVacation(){$('editingVacationId').value='';$('vacationFormTitle').textContent='Neuen Urlaub eintragen';$('vacationType').value='Urlaub';$('vacationScope').value='full';$('vacationStatus').value='Beantragt';$('vacationNote').value='';$('vacationForm').classList.remove('hidden')}
function closeVacationForm(){$('vacationForm').classList.add('hidden');$('editingVacationId').value=''}
function saveVacation(){const id=Number($('editingVacationId').value),employeeId=Number($('vacationEmployee').value),from=$('vacationFrom').value,to=$('vacationTo').value,type=$('vacationType').value,scope=$('vacationScope').value,status=$('vacationStatus').value,note=$('vacationNote').value.trim();if(!employeeId||!from||!to)return alert('Bitte Mitarbeiter und Zeitraum auswählen.');if(localDate(to)<localDate(from))return alert('Das Enddatum liegt vor dem Startdatum.');const e=emp(employeeId),conflicts=state.vacations.filter(v=>v.id!==id&&emp(v.employeeId)?.department===e.department&&v.status!=='Geplant'&&!(localDate(v.to)<localDate(from)||localDate(v.from)>localDate(to)));if(conflicts.length>=2&&!confirm(`Warnung: In ${e.department} gibt es bereits ${conflicts.length} überschneidende Einträge. Trotzdem speichern?`))return;if(id){const v=state.vacations.find(x=>x.id===id);const old=period(v.from,v.to),changed=v.from!==from||v.to!==to;Object.assign(v,{employeeId,from,to,type,scope,status,note});if(changed){const reason=prompt('Grund für die Verschiebung:','Personelle Abstimmung')||'Nicht angegeben';const initiator=confirm('Wurde die Verschiebung vom Betrieb veranlasst?\nOK = Betrieb, Abbrechen = Mitarbeiter')?'Betrieb':'Mitarbeiter';state.moves.push({id:Date.now(),employeeId,oldPeriod:old,newPeriod:period(from,to),reason,initiator})}}else state.vacations.push({id:Date.now(),employeeId,from,to,type,scope,status,note});saveState();closeVacationForm();renderAll()}
window.editVacation=id=>{const v=state.vacations.find(x=>x.id===id);if(!v)return;$('departmentFilter').value=emp(v.employeeId)?.department||state.departments[0];renderCalendar();$('editingVacationId').value=id;$('vacationEmployee').value=v.employeeId;$('vacationFrom').value=v.from;$('vacationTo').value=v.to;$('vacationType').value=v.type;$('vacationScope').value=v.scope||'full';$('vacationStatus').value=v.status;$('vacationNote').value=v.note||'';$('vacationFormTitle').textContent='Urlaub bearbeiten oder verschieben';$('vacationForm').classList.remove('hidden');$('vacationForm').scrollIntoView({behavior:'smooth'})}
window.approveVacation=id=>{const v=state.vacations.find(x=>x.id===id);if(v){v.status='Genehmigt';saveState();renderAll()}}
window.deleteVacation=id=>{if(!confirm('Urlaubseintrag löschen?'))return;state.vacations=state.vacations.filter(v=>v.id!==id);saveState();renderAll()}
function renderWeek(){const selected=localDate($('weekDate').value),day=(selected.getDay()+6)%7,monday=new Date(selected);monday.setDate(selected.getDate()-day);const dates=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);return d});$('weekSummary').innerHTML=`<div class="notice">Woche ${dates[0].toLocaleDateString('de-DE')} bis ${dates[6].toLocaleDateString('de-DE')}</div>`;let h='<thead><tr><th>Abteilung</th>'+dates.map(d=>`<th>${d.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}</th>`).join('')+'</tr></thead><tbody>';for(const dep of state.departments){h+=`<tr><td>${esc(dep)}</td>`;for(const d of dates){const names=state.vacations.filter(v=>v.status!=='Geplant'&&inRange(d,v.from,v.to)&&emp(v.employeeId)?.department===dep).map(v=>emp(v.employeeId)?.name);h+=`<td class="${names.length>=3?'critical':names.length?'vacation':''}">${names.map(esc).join('<br>')||'–'}</td>`}h+='</tr>'}$('weekTable').innerHTML=h+'</tbody>'}
function renderLeaders(){const leaders=state.employees.filter(e=>e.leader);$('leaderTable').innerHTML='<thead><tr><th>Name</th><th>Abteilung</th><th>Vertretung</th><th>Nächster Urlaub</th><th>Status</th></tr></thead><tbody>'+leaders.map(e=>{const v=vacsFor(e.id).sort((a,b)=>localDate(a.from)-localDate(b.from))[0];return `<tr><td>${esc(e.name)}</td><td>${esc(e.department)}</td><td>${esc(e.substitute||'Keine')}</td><td>${v?period(v.from,v.to):'–'}</td><td>${v?statusBadge(v.status):'<span class="badge">Anwesend</span>'}</td></tr>`}).join('')+'</tbody>';const m=leaderOverlapCount();$('leaderWarnings').innerHTML=m>=2?`<div class="warning warning-danger"><strong>Warnung:</strong> Bis zu ${m} Leiter gleichzeitig abwesend.</div>`:'<div class="warning"><strong>Leiterbesetzung:</strong> Keine kritische Überschneidung.</div>'}
function addMove(){const employeeId=Number($('moveEmployee').value),oldPeriod=$('moveOld').value.trim(),newPeriod=$('moveNew').value.trim(),reason=$('moveReason').value.trim(),initiator=$('moveInitiator').value;if(!employeeId||!oldPeriod||!newPeriod)return alert('Bitte Mitarbeiter sowie alten und neuen Zeitraum angeben.');state.moves.push({id:Date.now(),employeeId,oldPeriod,newPeriod,reason:reason||'Nicht angegeben',initiator});saveState();$('moveOld').value=$('moveNew').value=$('moveReason').value='';renderHistory()}
function renderHistory(){$('historyTable').innerHTML='<thead><tr><th>Mitarbeiter</th><th>Alter Zeitraum</th><th>Neuer Zeitraum</th><th>Grund</th><th>Veranlasst durch</th></tr></thead><tbody>'+state.moves.map(m=>`<tr><td>${esc(emp(m.employeeId)?.name)}</td><td>${esc(m.oldPeriod)}</td><td>${esc(m.newPeriod)}</td><td>${esc(m.reason)}</td><td>${esc(m.initiator)}</td></tr>`).join('')+'</tbody>';const counts={};state.moves.filter(m=>m.initiator==='Betrieb').forEach(m=>counts[m.employeeId]=(counts[m.employeeId]||0)+1);$('fairnessWarnings').innerHTML=Object.entries(counts).filter(([,n])=>n>=2).map(([id,n])=>`<div class="warning"><strong>Fairness:</strong> ${esc(emp(id)?.name)} wurde bereits ${n}-mal betrieblich verschoben.</div>`).join('')}
function renderDepartments(){$('departmentTable').innerHTML='<thead><tr><th>Abteilung</th><th>Mindestbesetzung</th><th>Mitarbeiter</th><th>Leiter</th><th>Aktion</th></tr></thead><tbody>'+state.departments.map((d,i)=>{const es=state.employees.filter(e=>e.department===d),min=Number(state.departmentSettings?.[d]??2);return `<tr><td>${esc(d)}</td><td>${min}</td><td>${es.length}</td><td>${esc(es.filter(e=>e.leader).map(e=>e.name).join(', ')||'–')}</td><td><button class="button tiny" onclick="renameDepartment(${i})">Umbenennen</button> <button class="button tiny" onclick="editDepartmentMinimum(${i})">Mindestbesetzung</button> <button class="button tiny danger" onclick="deleteDepartment(${i})">Löschen</button></td></tr>`}).join('')+'</tbody>'}
function addDepartment(){const name=$('newDepartment').value.trim();if(!name)return alert('Bitte einen Namen eingeben.');if(state.departments.includes(name))return alert('Diese Abteilung existiert bereits.');state.departments.push(name);state.departmentSettings[name]=Math.max(0,Number($('newDepartmentMin').value||0));$('newDepartment').value='';saveState();renderAll()}
window.renameDepartment=i=>{const old=state.departments[i],name=prompt('Neuer Name der Abteilung:',old)?.trim();if(!name||name===old)return;if(state.departments.includes(name))return alert('Der Name existiert bereits.');state.departments[i]=name;state.employees.filter(e=>e.department===old).forEach(e=>e.department=name);state.departmentSettings[name]=state.departmentSettings[old]??2;delete state.departmentSettings[old];saveState();renderAll()}
window.editDepartmentMinimum=i=>{const d=state.departments[i],current=Number(state.departmentSettings?.[d]??2),value=prompt(`Mindestbesetzung für „${d}“:`,current);if(value===null)return;const n=Number(value);if(!Number.isFinite(n)||n<0)return alert('Bitte eine gültige Zahl ab 0 eingeben.');state.departmentSettings[d]=Math.floor(n);saveState();renderAll()}
window.deleteDepartment=i=>{const d=state.departments[i];if(state.departments.length<=1)return alert('Die letzte Abteilung kann nicht gelöscht werden.');const assigned=state.employees.filter(e=>e.department===d),targets=state.departments.filter(x=>x!==d);let target='';if(assigned.length){target=prompt(`${assigned.length} Mitarbeiter sind „${d}“ zugeordnet. Gib die Zielabteilung für die Übertragung ein:

${targets.join(', ')}`,targets[0])?.trim()||'';if(!targets.includes(target))return alert('Löschen abgebrochen: Die Zielabteilung wurde nicht gefunden.')}if(!confirm(`Abteilung „${d}“ wirklich löschen?${assigned.length?`
${assigned.length} Mitarbeiter werden nach „${target}“ verschoben.`:''}`))return;assigned.forEach(e=>e.department=target);state.departments.splice(i,1);delete state.departmentSettings[d];saveState();renderAll()}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportBackup(){download(`Urlaubsplaner-Sicherung-${iso(new Date())}.json`,JSON.stringify(state,null,2),'application/json');$('backupStatus').textContent='Sicherung wurde erstellt.'}
function importBackup(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{state=normalize(JSON.parse(r.result));saveState();fillLogin();renderAll();$('backupStatus').textContent='Sicherung erfolgreich importiert.'}catch{$('backupStatus').textContent='Ungültige Sicherungsdatei.'}};r.readAsText(file)}
function exportCsv(){const dep=$('departmentFilter').value,ids=state.employees.filter(e=>e.department===dep).map(e=>e.id),rows=[['Mitarbeiter','Abteilung','Von','Bis','Urlaubstage','Umfang','Art','Status','Notiz']];state.vacations.filter(v=>ids.includes(v.employeeId)).forEach(v=>rows.push([emp(v.employeeId)?.name,dep,v.from,v.to,vacationDays(v),v.scope==='full'?'Ganzer Tag':'Halber Tag',v.type,v.status,v.note]));const csv='\ufeff'+rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(';')).join('\r\n');download(`Urlaubsplan-${dep}.csv`,csv,'text/csv;charset=utf-8')}
function resetData(){if(!confirm('Alle lokalen Änderungen löschen und Testdaten wiederherstellen?'))return;state=normalize(window.DEFAULT_DATA);OLD_STORES.forEach(k=>localStorage.removeItem(k));saveState();fillLogin();clearEmployeeForm();renderAll();$('backupStatus').textContent='Testdaten wurden wiederhergestellt.'}
init();
